"""initial_schema

Revision ID: baceca7a212f
Revises: 
Create Date: 2026-09-03 12:51:55.579318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baceca7a212f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_phone_number'), 'businesses', ['phone_number'], unique=True)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone_number', name='uq_customers_business_phone')
    )
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_table('customer_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_preferences_customer_id'), 'customer_preferences', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_preferences_day_of_week'), 'customer_preferences', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_customer_preferences_service_id'), 'customer_preferences', ['service_id'], unique=False)
    op.create_index(op.f('ix_customer_preferences_time_slot'), 'customer_preferences', ['time_slot'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SENDING', 'CLAIMED', 'EXPIRED', 'CANCELLED', name='slot_status'), nullable=False),
    sa.Column('claimed_by_customer_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claimed_by_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_business_id'), 'slots', ['business_id'], unique=False)
    op.create_index(op.f('ix_slots_claimed_by_customer_id'), 'slots', ['claimed_by_customer_id'], unique=False)
    op.create_index(op.f('ix_slots_service_id'), 'slots', ['service_id'], unique=False)
    op.create_index(op.f('ix_slots_start_time'), 'slots', ['start_time'], unique=False)
    op.create_index(op.f('ix_slots_status'), 'slots', ['status'], unique=False)
    op.create_table('broadcast_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('message_sid', sa.String(length=100), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_logs_customer_id'), 'broadcast_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_message_sid'), 'broadcast_logs', ['message_sid'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_slot_id'), 'broadcast_logs', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_logs_slot_id'), table_name='broadcast_logs')
    op.drop_index(op.f('ix_broadcast_logs_message_sid'), table_name='broadcast_logs')
    op.drop_index(op.f('ix_broadcast_logs_customer_id'), table_name='broadcast_logs')
    op.drop_table('broadcast_logs')
    op.drop_index(op.f('ix_slots_status'), table_name='slots')
    op.drop_index(op.f('ix_slots_start_time'), table_name='slots')
    op.drop_index(op.f('ix_slots_service_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_claimed_by_customer_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_business_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_customer_preferences_time_slot'), table_name='customer_preferences')
    op.drop_index(op.f('ix_customer_preferences_service_id'), table_name='customer_preferences')
    op.drop_index(op.f('ix_customer_preferences_day_of_week'), table_name='customer_preferences')
    op.drop_index(op.f('ix_customer_preferences_customer_id'), table_name='customer_preferences')
    op.drop_table('customer_preferences')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_phone_number'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
